### ISSUE TITLE
Running App

### ISSUE THREAD

**Issue by fjames003** [bburan/abr#1]
Hello, I have been trying to get your ABR program running but keep seeming to run into environment issues. After running the setup.py and then trying to run abr_gui, I get the following error:

Traceback (most recent call last):
  File "/usr/local/bin/abr_gui", line 11, in <module>
    load_entry_point('ABR==0.0.0', 'console_scripts', 'abr_gui')()
  File "/home/fjames/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/fjames/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/home/fjames/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/home/fjames/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'abr.app'

Could you provide any insight?

**Comment by bburan** [comment]
Yes, there are probably some bugs in the setup.py script because I have
only been testing this via "python setup.py develop" (as opposed to "python
setup.py install" or pip install". I have some very recent changes that may
fix this. I'll push these changes either Friday or next week.

**Comment by fjames003** [comment]
So I actually found what the issue was, the PYTHONPATH is not getting updated correctly by the setup.py script. In 'packages' you need to include abr.app and abr.parsers and this will solve the above issue however you will still get a "ModuleNotFoundError" saying "No module named 'abr.main_window'" however this can be resolved by `export PYTHONPATH=/path/to/abr` and then everything will work after a few minor tweaks. I am not sure how to avoid the explicit export though.

**Comment by bburan** [comment]
Thanks. It has to do with not finding some enaml files. I'll fix it when I
get a chance.

**Comment by bburan** [comment]
@fjames003 I pushed some changes that should fix the issues you're reporting. This version of the program is in development, so you may find a few additional bugs. Please report as you find them. Are you using this with ABR files generated using the EPL CFTS?
