### ISSUE TITLE
Windows 10 file loading error.

### ISSUE THREAD

**Issue by Valstl** [bburan/abr#2]
Hello,
when I try to load the example file for analysis I receive that type of error. 

subprocess.CalledProcessError: Command '['abr_loop', '--skip-errors', 'D:/jupyter/abr', '--parser', 'EPL', '--user', 'vm',
'--highpass', '300', '--lowpass', '3000', '--waves', '1']' returned non-zero exit status 1.

Thanks,
Valentin

**Comment by bburan** [comment]
@Valstl I just pushed a commit to the repo that should fix the bug. It was an import error due to a deprecation in Python.
