### ISSUE TITLE
Atom.compat error

### ISSUE THREAD

**Issue by orhunkose** [bburan/abr#3]
Hello, I wanted to use your peak analysis tool, and I installed everything, but it seems to give an error "module atom.compat could not be found". I checked the "Atom" py library, and compat module is nowhere to be found.

**Comment by orhunkose** [comment]
Nevermind, it was a version issue. If you specifically install "atom==0.4.3", it works. I had 0.5.0 and that was the problem. I hope they make it compatible with this library again.

**Comment by bburan** [comment]
Thanks @orhunkose. This must be a relatively recent release of Atom. I don't use the compat module, so it's likely a third-party library (e.g., Enaml) may need to be updated to work with Atom 0.5.0.

**Comment by bburan** [comment]
Likely the cause of the problem.

https://github.com/nucleic/atom/issues/100

**Comment by orhunkose** [comment]
Yeah, that seems to be the issue. I still don't see the fix in the current version (June). Maybe the issue persists with every iteration.
